apiVersion: v1
kind: Pod
metadata:
  name: preprocessing
  namespace: ncdc-use-case-1
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: "vbm"
  containers:
  # - name: input-watcher
  #   image: busybox
  #   command: ['sh', '-c', 'until [[ -d /mnt/data/input ]]; do echo waiting for the input; sleep 10; done;']
  #   volumeMounts:
  #   - name: data
  #     mountPath: "/mnt/data"
  #     subPath: "."
  - name: pre-processing
    # 0.0.12: Working version to run the VBM pipeline
    # 0.0.13: Included the quality check scripts
    image: pmateus/memorabel-mri-preprocessing:0.0.14
    # command: ['bash', '-c', 'until [ -d /mnt/data/input ]; do echo waiting for the input; sleep 10; done; python3 start.py;']
    command: ['bash', '-c', 'until [ -d /mnt/data/close ]; do echo waiting; sleep 300; done; rm -r /mnt/data/close;']
    volumeMounts:
    - name: data
      mountPath: "/mnt/data"
      subPath: "."
    env:
      - name: JOBS
        value: "1"
      - name: INPUT
        value: "/mnt/data/input"
      - name: SAVE_PATH
        value: "/mnt/data/output"
      - name: LOG_PATH
        value: "/mnt/data/logs"
  restartPolicy: Never