version: "3.8"

services:
  db:
    image: postgres:12.6
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

  memorabel-parser:
    image: pmateus/memorabel-data-harmonization:1.0.0
    stdin_open: true
    tty: true
    environment:
      DB_USER: postgres
      DB_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: CDM
      DOCKER_ENV: "true"
      VOCABULARY_PATH: /usr/src/app/vocabularies
      DESTINATION_MAPPING_PATH: /mnt/mappings/destination_mapping.csv
      SOURCE_MAPPING_PATH: /mnt/mappings/source_mapping.csv
      DATASET_PATH: /mnt/data/dataset.csv
    volumes:
      - $PWD/mappings:/mnt/mappings
      - $PWD/data:/mnt/data
    depends_on:
      - db
      - adminer
